[[redirects]]
from = "/*"
to = "/*"
status = 200
headers = { Access-Control-Allow-Origin = "*", Authorization = "Bearer api-key"}

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Authorization = "Bearer api-key"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Authorization = "Bearer api-key"