[[redirects]]
  from = "/*"
  to = "/*"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  functions = "built-lambda" 
  publish = "build"