[[redirects]]
  from = "/*"
  to = "/stream/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[build]
  functions = "built-lambda" 
  publish = "build"